name: thamesdeltaworldservice
favicon: null
layout_spectrum: 0.13363682734780014
typography_spectrum: 0.08396825334057212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1261055050417781
  lightness: 0.22373309219256043
  saturation: 0.1504963943734765
  rhythmicContrast: 0.8232177931349725
purpose: []
