name: thamesdeltaworldservice
favicon: null
layout_spectrum: 0.70793
typography_spectrum: 0.52153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#565656'
    - '#e5e5e5'
    - '#71943d'
    - '#daa35c'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.8232177931349725
purpose: []
