title: Thames Delta World Service
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5202361
  brandStrength: 0.8456998
  lightness: 0.6956155
  brandColors:
    - '#391502'
    - '#FCFA91'
    - '#C7BC4B'
    - '#A2A3C6'
    - '#77651F'
  rhythmicContrast: 0.8827993
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: thamesdeltaworldservice
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2150084
layout_spectrum: 1
